[rack]
bitrate=48000

[[instruments]]
type="Mixer"
name="mixer"

[[instruments]]
type="RawSource"
name="generator1"
[instruments.parameters]
frequency=500
waveform=2

# [source instrument, source port, target instrument, target port]
[connections]
endpoints = [
    # Connect generator1 with mixer channel 1
    ["generator1",  "OUT_LEFT", "mixer", "IN_LEFT_01" ],
    ["generator1", "OUT_RIGHT", "mixer", "IN_RIGHT_01" ],

    # MAIN AUDIO OUT
    ["mixer", "OUT_LEFT", "__AUDIO_OUT", "IN_LEFT" ],
    ["mixer", "OUT_RIGHT", "__AUDIO_OUT", "IN_RIGHT" ],
]

[sequencer]
tempo=120
meter={ numerator = 3, denominator = 4 }

[[sequencer.clips]]
start={ bar = 1, beat = 1, offset = 0.0 }
end={ bar = 9, beat = 2, offset = 0.0 } 
target = "generator1"

[sequencer.clips.pattern]
period = 1
command = "set"
events = [
    { parameter = "frequency", value = 392.00 },
    { },
    { parameter = "frequency", value = 440.00 },
    { parameter = "frequency", value = 392.00 },
    { parameter = "frequency", value = 523.25 },
    { parameter = "frequency", value = 493.88 },

    { parameter = "frequency", value = 392.00 },
    { },
    { parameter = "frequency", value = 440.00 },
    { parameter = "frequency", value = 392.00 },
    { parameter = "frequency", value = 587.33 },
    { parameter = "frequency", value = 523.25 },

    { parameter = "frequency", value = 392.00 },
    { },
    { parameter = "frequency", value = 784.00 },
    { parameter = "frequency", value = 659.26 },
    { parameter = "frequency", value = 523.25 },
    { parameter = "frequency", value = 493.88 },
    { parameter = "frequency", value = 440.00 },

    { parameter = "frequency", value = 698.46 },
    { },
    { parameter = "frequency", value = 659.26 },
    { parameter = "frequency", value = 523.25 },
    { parameter = "frequency", value = 587.33 },
    { parameter = "frequency", value = 523.25 },
]

[[sequencer.clips]]
start={ bar = 1, beat = 1, offset = 0.0 }
end={ bar = 9, beat = 2, offset = 0.0 } 
target = "generator1"

# Alternate between waveforms every 1/8 beat
[sequencer.clips.pattern]
period = 0.125
command = "set"
events = [
    { parameter = "waveform", value = 2.0 },
    { parameter = "waveform", value = 1.0 },
]