[rack]

[[instruments]]
type="RawSource"
name="LFO0"
[instruments.parameters]
frequency=0.1
waveform=1

[[instruments]]
type="RawSource"
name="LFO1"
[instruments.parameters]
frequency=10
waveform=1

[[instruments]]
type="RawSource"
name="raw_source"
[instruments.parameters]
frequency=200
waveform=3

# [source instrument, source port, target instrument, target port]
[connections]
endpoints = [
    # Connect LFO
    ["LFO0", "OUT_LEFT", "LFO1", "IN_CV"],
    ["LFO1", "OUT_LEFT", "raw_source", "IN_CV"],

    # MAIN AUDIO OUT
    ["raw_source", "OUT_LEFT", "__AUDIO_OUT", "IN_LEFT" ],
    ["raw_source", "OUT_RIGHT", "__AUDIO_OUT", "IN_RIGHT" ],
]

[sequencer]
tempo=120
meter={ numerator = 3, denominator = 4 }

[[sequencer.clips]]
start={ bar = 1, beat = 1, offset = 0.0 }
end={ bar = 100, beat = 2, offset = 0.0 } 
target = "raw_source"

# Alternate between fm depth
[sequencer.clips.pattern]
period = 1
command = "set"
events = [
    { parameter = "fm_depth", value = 0.0 },
    { parameter = "fm_depth", value = 0.25 },
    { parameter = "fm_depth", value = 0.5 },
    { parameter = "fm_depth", value = 1.0 },
]