[rack]
bitrate=48000

[[instruments]]
type="RawSource"
name="raw_source"
[instruments.parameters]
frequency=440
waveform=2

# [source instrument, source port, target instrument, target port]
[connections]
endpoints = [
    # MAIN AUDIO OUT
    ["raw_source", "OUT_LEFT", "__AUDIO_OUT", "IN_LEFT" ],
    ["raw_source", "OUT_RIGHT", "__AUDIO_OUT", "IN_RIGHT" ],
]