[rack]
bitrate=48000

[[instruments]]
type="Mixer"
name="mixer"

[[instruments]]
type="SignalSource"
name="generator1"
[instruments.parameters]
frequency=2000

[[instruments]]
type="SignalSource"
name="generator2"
[instruments.parameters]
frequency=10000

# [source instrument, source port, target instrument, target port]
[connections]
endpoints = [
    # Connect generator1 with mixer channel 1
    ["generator1",  "OUT_LEFT", "mixer", "IN_LEFT_01" ],
    ["generator1", "OUT_RIGHT", "mixer", "IN_RIGHT_01" ],

    # Connect generator2 with mixer channel 2
    ["generator2", "OUT_LEFT", "mixer", "IN_LEFT_02" ],
    ["generator2", "OUT_RIGHT", "mixer", "IN_RIGHT_02" ],

    # MAIN AUDIO OUT
    ["mixer", "OUT_LEFT", "__AUDIO_OUT", "IN_LEFT" ],
    ["mixer", "OUT_RIGHT", "__AUDIO_OUT", "IN_RIGHT" ],
]

[sequencer]
tempo=120
meter={ numerator = 4, denominator = 4 }

[[sequencer.clips]]
start={ bar = 1, beat = 1, offset = 0.0 }
end={ bar = 8, beat = 1, offset = 0.0 } 
target = "generator1"

[sequencer.clips.pattern]
period = 1
command = "set"

events = [
    { parameter = "frequency", value = 98.00 },
    { parameter = "frequency", value = 98.00 },
    { parameter = "frequency", value = 110.00 },
    { parameter = "frequency", value = 98.00 },
    { parameter = "frequency", value = 130.81 },
    { parameter = "frequency", value = 123.47 },

    { parameter = "frequency", value = 98.00 },
    { parameter = "frequency", value = 98.00 },
    { parameter = "frequency", value = 110.00 },
    { parameter = "frequency", value = 98.00 },
    { parameter = "frequency", value = 146.83 },
    { parameter = "frequency", value = 130.81 },

    { parameter = "frequency", value = 98.00 },
    { parameter = "frequency", value = 98.00 },
    { parameter = "frequency", value = 196.00 },
    { parameter = "frequency", value = 164.81 },
    { parameter = "frequency", value = 130.81 },
    { parameter = "frequency", value = 123.47 },
    { parameter = "frequency", value = 110.00 },

    { parameter = "frequency", value = 174.61 },
    { parameter = "frequency", value = 174.61 },
    { parameter = "frequency", value = 164.81 },
    { parameter = "frequency", value = 130.81 },
    { parameter = "frequency", value = 146.83 },
    { parameter = "frequency", value = 130.81 },
]